language: php

php:
  - 5.6
  - 7.0

dist: trusty

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6


before_script:
  - travis_retry composer self-update
  - cp .env.travis .env
  - mysql -u root -e 'create database testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script: vendor/bin/phpunit
